version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=itmo_user
      - POSTGRES_PASSWORD=itmo_pass
      - POSTGRES_DB=itmo_db
    volumes:
      - itmo_pgdata:/var/lib/postgresql/data
    networks:
      - itmo_net

  backend:
    build:
      context: ./project-name
      dockerfile: Dockerfile
    image: itmo_backend:latest
    volumes:
      - ./project-name:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=itmo_user
      - DATABASE_PASSWORD=itmo_pass
      - DATABASE_NAME=itmo_db
    networks:
      - itmo_net

  frontend:
    build:
      context: ./my-vue-app
      dockerfile: Dockerfile
    image: itmo_frontend:latest
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - ./my-vue-app:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:3000/video
    networks:
      - itmo_net

networks:
  itmo_net:
    driver: bridge

volumes:
  itmo_pgdata:
